- name: Check if OpenJDK 21 is installed
  command: dpkg -l | grep openjdk-21-jdk
  register: openjdk_installed
  ignore_errors: yes

- name: Install OpenJDK 21 if not installed
  apt:
    name: openjdk-21-jdk
    state: present
    update_cache: yes
  when: openjdk_installed.rc != 0

- name: Check if Android Studio is installed via Snap
  command: snap list android-studio
  register: android_studio_installed
  ignore_errors: yes

- name: Install Android Studio via Snap if not installed
  snap:
    name: android-studio
    classic: yes
    state: present
  when: android_studio_installed.rc != 0