- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    state: latest

- name: Download Docker GPG key to keyrings directory
  ansible.builtin.shell:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null"
    creates: /etc/apt/keyrings/docker.asc
  become: yes
  register: download_docker_key

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
  become: yes
  register: add_docker_repo

- name: Force apt update and install Docker
  ansible.builtin.shell: |
    apt update -y
    apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  become: yes
  register: apt_update_install
  retries: 5
  delay: 10
  until: apt_update_install.rc == 0
  failed_when: apt_update_install.rc != 0

- name: Add current user to the docker group
  ansible.builtin.user:
    name: "{{ username }}"
    group: docker
    append: yes
  become: yes
