- name: Check if VS Code is installed
  command: dpkg-query -W code
  register: is_installed
  failed_when: false
  changed_when: false

- name: Download VS Code deb package
  get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: /tmp/vscode.deb
  when: is_installed.rc != 0

- name: Install VS Code package
  apt:
    deb: /tmp/vscode.deb
    state: present
  when: is_installed.rc != 0

- name: Clean up downloaded deb
  file:
    path: /tmp/vscode.deb
    state: absent
  when: is_installed.rc != 0